# Site settings
title: Ali Sinan Köksal
email: koksal@cs.berkeley.edu
description: "Ali Sinan Köksal, Software Engineer at Google, UC Berkeley Computer Science PhD."
baseurl: ""
url: "https://koksal.org/"
timezone: America/Los_Angeles

analyticsID: "UA-25937299-1"

# Build settings
markdown: kramdown
permalink: pretty
production: true

exclude:
  - bower_components
  - node_modules
  - package.json
  - bower.json
  - Gruntfile.js
  - README.md
  - setup
